#!/usr/bin/env python3
"""Generate architecture discovery reports for the OFBiz migration."""

from __future__ import annotations

import os
import xml.etree.ElementTree as ET
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "migration" / "discovery"


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def local_name(tag: str) -> str:
    return tag.rsplit("}", 1)[-1]


def parse_xml(path: Path) -> ET.Element | None:
    try:
        return ET.parse(path).getroot()
    except (ET.ParseError, OSError):
        return None


def children_named(root: ET.Element, name: str) -> list[ET.Element]:
    return [child for child in list(root) if local_name(child.tag) == name]


def descendants_named(root: ET.Element, name: str) -> list[ET.Element]:
    return [node for node in root.iter() if local_name(node.tag) == name]


def is_enabled(component_dir: Path) -> bool:
    component_file = component_dir / "ofbiz-component.xml"
    root = parse_xml(component_file)
    if root is None:
        return False
    return root.attrib.get("enabled", "true") == "true"


def discover_active_components() -> list[Path]:
    loader = ROOT / "framework" / "base" / "config" / "component-load.xml"
    root = parse_xml(loader)
    if root is None:
        return []

    components: list[Path] = []
    for load_components in children_named(root, "load-components"):
        parent = ROOT / load_components.attrib["parent-directory"]
        nested_loader = parent / "component-load.xml"
        if nested_loader.exists():
            nested_root = parse_xml(nested_loader)
            if nested_root is None:
                continue
            for load_component in children_named(nested_root, "load-component"):
                component = parent / load_component.attrib["component-location"]
                if is_enabled(component):
                    components.append(component)
        elif parent.exists():
            for component in sorted([path for path in parent.iterdir() if path.is_dir()]):
                if is_enabled(component):
                    components.append(component)

    start_component = ROOT / "framework" / "start"
    if start_component.exists():
        components.append(start_component)

    return components


def component_root(component: Path) -> ET.Element | None:
    return parse_xml(component / "ofbiz-component.xml")


def generate_components(components: list[Path]) -> None:
    lines = [
        "# OFBiz Component Inventory",
        "",
        "Generated by: `migration/discovery/generate_discovery.py`",
        "",
        "| Component | Path | Webapps | Entity resources | Service resources | Containers | Tests |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: |",
    ]

    for component in components:
        root = component_root(component)
        if root is None:
            lines.append(f"| `{component.name}` | `{rel(component)}` | 0 | 0 | 0 | 0 | 0 |")
            continue
        name = root.attrib.get("name", component.name)
        webapps = len(children_named(root, "webapp"))
        entities = len(children_named(root, "entity-resource"))
        services = len(children_named(root, "service-resource"))
        containers = len(children_named(root, "container"))
        tests = len(children_named(root, "test-suite"))
        lines.append(
            f"| `{name}` | `{rel(component)}` | {webapps} | {entities} | {services} | {containers} | {tests} |"
        )

    write_report("components.md", lines)


def generate_routes(components: list[Path]) -> None:
    lines = [
        "# OFBiz Web Route Inventory",
        "",
        "Generated by: `migration/discovery/generate_discovery.py`",
        "",
    ]

    for component in components:
        root = component_root(component)
        if root is None:
            continue
        webapps = children_named(root, "webapp")
        if not webapps:
            continue
        component_name = root.attrib.get("name", component.name)
        lines.extend([f"## `{component_name}`", ""])
        for webapp in webapps:
            location = component / webapp.attrib.get("location", "")
            controller = location / "WEB-INF" / "controller.xml"
            mount = webapp.attrib.get("mount-point", "")
            lines.extend([
                f"### `{webapp.attrib.get('name', location.name)}`",
                "",
                f"- Mount point: `{mount}`",
                f"- Location: `{rel(location) if location.exists() else rel(location)}`",
                f"- Controller: `{rel(controller) if controller.exists() else 'missing'}`",
                "",
            ])
            controller_root = parse_xml(controller)
            if controller_root is None:
                continue
            lines.extend([
                "| URI | Auth | HTTPS | Event | Success target |",
                "| --- | --- | --- | --- | --- |",
            ])
            for request_map in descendants_named(controller_root, "request-map"):
                security_nodes = children_named(request_map, "security")
                security = security_nodes[0] if security_nodes else None
                event_nodes = children_named(request_map, "event")
                response_nodes = children_named(request_map, "response")
                success = next((node for node in response_nodes if node.attrib.get("name") == "success"), None)
                event = ""
                if event_nodes:
                    event = event_nodes[0].attrib.get("invoke", "") or event_nodes[0].attrib.get("path", "")
                lines.append(
                    "| `{}` | `{}` | `{}` | `{}` | `{}` |".format(
                        request_map.attrib.get("uri", ""),
                        security.attrib.get("auth", "") if security is not None else "",
                        security.attrib.get("https", "") if security is not None else "",
                        event,
                        success.attrib.get("value", "") if success is not None else "",
                    )
                )
            lines.append("")

    write_report("routes.md", lines)


def generate_services(components: list[Path]) -> None:
    lines = [
        "# OFBiz Service Inventory",
        "",
        "Generated by: `migration/discovery/generate_discovery.py`",
        "",
    ]

    for component in components:
        root = component_root(component)
        if root is None:
            continue
        resources = [
            component / node.attrib.get("location", "")
            for node in children_named(root, "service-resource")
            if node.attrib.get("type") == "model"
        ]
        if not resources:
            continue
        component_name = root.attrib.get("name", component.name)
        lines.extend([f"## `{component_name}`", "", "| Service | Engine | Location | Invoke | Auth |", "| --- | --- | --- | --- | --- |"])
        for resource in resources:
            resource_root = parse_xml(resource)
            if resource_root is None:
                continue
            for service in descendants_named(resource_root, "service"):
                lines.append(
                    "| `{}` | `{}` | `{}` | `{}` | `{}` |".format(
                        service.attrib.get("name", ""),
                        service.attrib.get("engine", ""),
                        service.attrib.get("location", ""),
                        service.attrib.get("invoke", ""),
                        service.attrib.get("auth", ""),
                    )
                )
        lines.append("")

    write_report("services.md", lines)


def generate_entities(components: list[Path]) -> None:
    lines = [
        "# OFBiz Entity Inventory",
        "",
        "Generated by: `migration/discovery/generate_discovery.py`",
        "",
    ]

    for component in components:
        root = component_root(component)
        if root is None:
            continue
        resources = [
            component / node.attrib.get("location", "")
            for node in children_named(root, "entity-resource")
            if node.attrib.get("type") == "model"
        ]
        if not resources:
            continue
        component_name = root.attrib.get("name", component.name)
        lines.extend([f"## `{component_name}`", "", "| Entity | Type | Package | Fields | Relations | Source |", "| --- | --- | --- | ---: | ---: | --- |"])
        for resource in resources:
            resource_root = parse_xml(resource)
            if resource_root is None:
                continue
            for node in resource_root.iter():
                kind = local_name(node.tag)
                if kind not in {"entity", "view-entity"}:
                    continue
                entity_name = node.attrib.get("entity-name", "")
                fields = len(children_named(node, "field"))
                relations = len(children_named(node, "relation"))
                lines.append(
                    "| `{}` | `{}` | `{}` | {} | {} | `{}` |".format(
                        entity_name,
                        kind,
                        node.attrib.get("package-name", ""),
                        fields,
                        relations,
                        rel(resource),
                    )
                )
        lines.append("")

    write_report("entities.md", lines)


def generate_integrations(components: list[Path]) -> None:
    patterns = {
        "jms": "JMS / messaging",
        "rmi": "RMI",
        "soap": "SOAP",
        "mail": "Email / JavaMail",
        "smtp": "SMTP",
        "ftp": "FTP/SFTP",
        "sftp": "FTP/SFTP",
        "paymentgateway": "Payment gateway",
        "shippinggateway": "Shipping gateway",
        "rest": "REST",
        "jaxrs": "JAX-RS",
        "jersey": "Jersey",
    }
    lines = [
        "# OFBiz Integration Inventory",
        "",
        "Generated by: `migration/discovery/generate_discovery.py`",
        "",
        "This report uses keyword scanning over XML/properties files. Treat it as a starting point for manual verification.",
        "",
        "| Area | File | Matched keyword |",
        "| --- | --- | --- |",
    ]

    search_roots = [ROOT / "framework", ROOT / "applications", ROOT / "themes", ROOT / "config"]
    files: list[Path] = []
    for search_root in search_roots:
        if search_root.exists():
            files.extend(
                path for path in search_root.rglob("*") if path.suffix.lower() in {".xml", ".properties", ".ftl", ".java", ".groovy"}
            )

    seen: set[tuple[str, str]] = set()
    for path in sorted(files):
        try:
            text = path.read_text(encoding="utf-8", errors="ignore").lower()
        except OSError:
            continue
        for keyword, area in patterns.items():
            if keyword in text and (rel(path), keyword) not in seen:
                seen.add((rel(path), keyword))
                lines.append(f"| `{area}` | `{rel(path)}` | `{keyword}` |")

    write_report("integrations.md", lines)


def generate_readme() -> None:
    lines = [
        "# Migration Discovery",
        "",
        "Generated discovery reports for the OFBiz-to-microservices migration.",
        "",
        "Run:",
        "",
        "```shell",
        "python3 migration/discovery/generate_discovery.py",
        "```",
        "",
        "Reports:",
        "",
        "- `components.md`: active OFBiz components and contributed resources.",
        "- `routes.md`: webapps, mount points, controller request maps.",
        "- `services.md`: service definitions and engines.",
        "- `entities.md`: entity and view-entity definitions.",
        "- `integrations.md`: keyword-based external integration inventory.",
    ]
    write_report("README.md", lines)


def write_report(name: str, lines: list[str]) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / name).write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> int:
    os.chdir(ROOT)
    components = discover_active_components()
    generate_readme()
    generate_components(components)
    generate_routes(components)
    generate_services(components)
    generate_entities(components)
    generate_integrations(components)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
