server {
    listen 8080 ssl;
    server_name localhost;

    ssl_certificate /tmp/local-gateway.crt;
    ssl_certificate_key /tmp/local-gateway.key;

    location /api/notifications/ {
        proxy_pass http://modern-notification-service:8080/api/notifications/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/accounting/invoices {
        proxy_pass http://modern-accounting-invoice-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /modern/accounting/invoices {
        proxy_pass http://modern-accounting-invoice-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /accounting/control/findInvoices {
        proxy_pass http://modern-accounting-invoice-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass https://legacy-ofbiz-app:8443;
        proxy_ssl_verify off;
        proxy_redirect https://localhost/ https://localhost:18080/;
        proxy_redirect https://localhost:8443/ https://localhost:18080/;
        proxy_redirect https://localhost:18443/ https://localhost:18080/;
        proxy_redirect https://legacy-ofbiz-app:8443/ https://localhost:18080/;
        proxy_set_header Accept-Encoding "";
        proxy_set_header Host localhost;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 18080;
        sub_filter 'https://localhost/' 'https://localhost:18080/';
        sub_filter 'https://localhost:8443/' 'https://localhost:18080/';
        sub_filter 'https://localhost:18443/' 'https://localhost:18080/';
        sub_filter 'http://localhost:18080/' 'https://localhost:18080/';
        sub_filter_once off;
    }
}
